name: Eleventy Build

on:
  push:
    branches:
      - main


jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build
        uses: maschmann/eleventy-build-action@main
        with:
          node_version: 23
          output: './www'
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: www 
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
